buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
        maven {
            name = "sonatype"
            url = "https://oss.sonatype.org/content/repositories/snapshots/"
        }
    }
    dependencies {
        classpath ('com.anatawa12.forge:ForgeGradle:1.2-1.1.+')
    }
}

apply plugin: 'forge'
targetCompatibility = sourceCompatibility =
compileJava.targetCompatibility = compileJava.sourceCompatibility = JavaVersion.VERSION_1_8

version = "0.7.0"
group = "ru.wertyfiregames.craftablecreatures"
archivesBaseName = "CraftableCreatures"

minecraft {
    version = "1.7.10-10.13.4.1614-1.7.10"
    runDir = "run"
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

build.doFirst {
    Scanner scanner = new Scanner(System.in);
    println 'Are you updated version numbers??? [y/n]'

    def input = scanner.nextLine()

    if (input.toLowerCase() == 'y') println 'Continuing build...'
    else if (input.toLowerCase() == 'n') {
        println 'Build cancelled'
        throw new GradleException('Build cancelled.')
    } else throw new GradleException('Incorrect input!')
}

repositories {
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
    maven {
        name = "wertyfireMaven"
        url = "https://raw.githubusercontent.com/Wertyfire/Versions/main/maven/"
    }
}

dependencies {
    //Wertyfire Core
    compile 'ru.wertyfiregames:wertyfire-core:1.7.10-1.0.2:dev'

    //NEI
    implementation 'codechicken:CodeChickenCore:1.7.10-1.0.7.48:dev'
    implementation 'codechicken:CodeChickenLib:1.7.10-1.1.3.140:dev'
    implementation 'codechicken:NotEnoughItems:1.7.10-1.0.5.120:dev'
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}