buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.1.6'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
targetCompatibility = sourceCompatibility =
compileJava.targetCompatibility = compileJava.sourceCompatibility = JavaVersion.VERSION_1_8

version = "1.0.1"
group= "ru.wertyfiregames.craftablecreatures"
archivesBaseName = "CraftableCreatures-1.8.9"

minecraft {
    version = "1.8.9-11.15.1.2318-1.8.9"
    runDir = "run"
    mappings = "stable_22"
    makeObfSourceJar = false
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

build.doFirst {
    Scanner scanner = new Scanner(System.in)
    println 'Are you updated version numbers??? [y/n]'

    def input = scanner.nextLine()

    if (input.toLowerCase() == 'y') println 'Continuing build...'
    else if (input.toLowerCase() == 'n') {
        println 'Build cancelled'
        throw new GradleException('Build cancelled.')
    } else throw new GradleException('Incorrect input!')
}

repositories {
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }
}

dependencies {
    //JEI
    implementation 'mezz.jei:jei_1.8.9:2.28.18.186'
}

processResources
{
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version,
        'mcversion':project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}